### ISSUE TITLE
Don't know how to run the project ! 

### ISSUE THREAD

**Issue by MohamedArbani** [mathworks/simulinkDroneReferenceApp#6]
Please ! Could someone help me in executing this project in MATLAB 2020 !!! urgent!

**Comment by pablorcum** [comment]
8ca8abe5574551769e57efb3d3965fbdf94739fd has been updated for MATLAB R2021b. Please give it a try and feel free to post any feedback.

**Comment by huang199701** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
