### ISSUE TITLE
why always github device authentication

### ISSUE THREAD

**Issue by aogrcs** [mathworks/simulinkDroneReferenceApp#8]
When I update this, it always let me authenticae! Could anyone help me, thanks

**Comment by huang199701** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huang199701** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
